version: '3.8'

services:
  app:
    image: "${DOCKER_USERNAME}/${DOCKER_IMAGE}"
    container_name: BARO_CONTAINER
    ports:
      - "8001:8001"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PROD_DATASOURCE_URL: "${PROD_DATASOURCE_URL}"
      PROD_DATASOURCE_USERNAME: "${PROD_DATASOURCE_USERNAME}"
      PROD_DATASOURCE_PASSWORD: "${PROD_DATASOURCE_PASSWORD}"
    networks:
      - baro-network
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - baro-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  baro-network:
