spring:
  application:
    name: baro
  profiles:
    group:
      local : local-db, dev-port, common
      dev: dev-db, dev-port, common
      prod: prod-db, prod-port,, common
    active: local
---
# 로컬용 DB
spring:
  config:
    activate:
      on-profile: local-db
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
---
# 개발용 DB
spring:
  config:
    activate:
      on-profile: dev-db
  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
---
# 배포용 DB
spring:
  config:
    activate:
      on-profile: prod-db
  datasource:
    url: ${PROD_DATASOURCE_USERNAME}
    username: ${PROD_DATASOURCE_USERNAME}
    password: ${PROD_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
---
# 공통 속성
spring:
  config:
    activate:
      on-profile: common
    import: application-secret.yml
  web:
    resources:
      add-mappings: false
jwt:
  secret: ${jwt.secret}
  access-token-expiration: ${jwt.access-token-expiration}
  refresh-token-expiration: ${jwt.refresh-token-expiration}
---
# 개발용 포트
spring:
  config:
    activate:
      on-profile: dev-port
server:
  port: 8000
---
# 배포용 포트
spring:
  config:
    activate:
      on-profile: prod-port
server:
  port: 8001