spring.application.name=BARO

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.syntax-highlight.theme=nord
springdoc.swagger-ui.urls-primary-name=TEST API
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.query-config-enabled=true
springdoc.pre-loading-enabled=true



